### ISSUE TITLE
Feature Request:

### ISSUE THREAD

**Issue by iluvatyr** [marklr/labelizer#1]
hey, this looks very nice and promising. 

Could you maybe give some data about how long the average library (10000-50000 pictures) would take to process with low-/mid-/high-end cpu/gpu?

**Comment by marklr** [comment]
On a CPU, `Intel(R) Xeon(R) CPU E3-1275 v5 @ 3.60GHz`, it takes about 5 seconds per image as things currently stand (2 models, 1 caption 1 vqa + about 10 prompts). Average image is a 5MB jpeg.

on a mac with `mps` it's about half that. I haven't yet tried on a CUDA-capable device but the code should definitely run. I've also added a basic streamlit runner to enable rapid prompt prototyping in the latest commits.
